CALL "%SC_PYJA_HM%\Config\JDK\x64\SSet-JDK-8.bat"
CALL "%SC_PYJA_HM%\Config\QtJambi\x64\SSet-QtJambi-4.8.7.bat"
SET SC_JAVA_XMX=-Xmx9g
SET SC_J_HM=%SC_J8_HM%
SET SC_J_X_FN=%SC_J8_X_FN%
SET SC_JC_X_FN=%SC_J8C_X_FN%
SET SC_JH_X_FN=%SC_J8H_X_FN%
SET SC_JR_X_FN=%SC_J8R_X_FN%
