CALL "%SC_PYJA_HM%\Config\JDK\x32\SSet-JDK-6.bat"
CALL "%SC_PYJA_HM%\Config\QtJambi\x32\SSet-QtJambi-4.5.2.bat"
SET SC_JAVA_XMX=-Xmx1400m
SET SC_J_HM=%SC_J6_HM%
SET SC_J_X_FN=%SC_J6_X_FN%
SET SC_JC_X_FN=%SC_J6C_X_FN%
SET SC_JH_X_FN=%SC_J6H_X_FN%
SET SC_JR_X_FN=%SC_J6R_X_FN%
