SET SC_PYTHON_HM=%SC_KAPA_HM%\19.01.22\Vindue\x64\Anaconda\5.1.0
SET SC_PYTHON_EXE_FN=%SC_PYTHON_HM%\python
SET QT_QPA_PLATFORM_PLUGIN_PATH=%SC_PYTHON_HM%\Library\plugins\platforms
SET SC_JEP_PN=%SC_PYTHON_HM%\Lib\site-packages\jep
SET SC_JEP_JAR_FN=%SC_JEP_PN%\jep-3.7.1.jar
