/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DgQt */

#ifndef _Included_DgQt
#define _Included_DgQt
#ifdef __cplusplus
extern "C" {
#endif
#undef DgQt_DC_CT_AC
#define DgQt_DC_CT_AC 0L
#undef DgQt_DC_CT_DC
#define DgQt_DC_CT_DC 1L
#undef DgQt_DC_CT_QC
#define DgQt_DC_CT_QC 2L
#undef DgQt_DC_CT_BQC
#define DgQt_DC_CT_BQC 3L
#undef DgQt_DC_CT_UC
#define DgQt_DC_CT_UC 128L
/*
 * Class:     DgQt
 * Method:    dp_i0
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i0
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     DgQt
 * Method:    dp_i1
 * Signature: (JLjava/lang/String;ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i1
  (JNIEnv *, jclass, jlong, jstring, jint, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i2
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i2
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i3
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i3
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i4
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i4
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i5
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i5
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i6
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i6
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i7
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i7
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i8
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i8
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i9
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i9
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     DgQt
 * Method:    dp_i10
 * Signature: (JLjava/lang/String;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_DgQt_dp_1i10
  (JNIEnv *, jclass, jlong, jstring, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
