@ECHO OFF
SETLOCAL

SET PATH=%SystemRoot%\system32

SET SC_THIS_BN=%~NX0
SET SC_THIS_JN=%~N0

PUSHD "%~DP0"
CD "%~DP0"
SET SC_TONO_HM=%CD%
CD %SC_TONO_HM%\..
SET SC_MILO_PN=%CD%
CD "%SC_MILO_PN%\..\..\.."
SET SC_PYJA_HM=%CD%
CD "%SC_PYJA_HM%\.."
SET SC_PYJA_RT=%CD%
FOR %%F IN (%SC_PYJA_RT%) DO SET SC_PYJA_NM=%%~NXF
FOR %%F IN (%SC_PYJA_HM%) DO SET SC_PYJA_VR=%%~NXF
POPD

CALL "%SC_PYJA_HM%\Config\SSet-KAPA.bat"
REM CALL "%SC_TONO_HM%\SSet-x32.bat"
CALL "%SC_TONO_HM%\SSet-x64.bat"

SET QT_AUTO_SCREEN_SCALE_FACTOR=1

SET PATH=%SC_PYTHON_HM%;%PATH%

SET SC_PATH=%PATH%

"%SC_PERL_EXE_FN%" "%SC_TONO_HM%\%SC_THIS_JN%.pl" %*

ENDLOCAL
