@ECHO OFF
SETLOCAL

SET PATH=%SystemRoot%\system32

SET SC_THIS_BN=%~NX0
SET SC_THIS_JN=%~N0

PUSHD "%~DP0"
CD "%~DP0"
SET SC_MILO_PN=%CD%
CD "%SC_MILO_PN%\..\..\.."
SET SC_PYJA_HM=%CD%
FOR %%F IN (%SC_PYJA_HM%) DO SET SC_PYJA_VR=%%~NXF
CD "%SC_PYJA_HM%\.."
SET SC_PYJA_RT=%CD%
FOR %%F IN (%SC_PYJA_RT%) DO SET SC_PYJA_NM=%%~NXF
POPD

CALL "%SC_PYJA_HM%\Config\SSet-KAPA.bat"
CALL "%SC_PYJA_HM%\Config\SSet-JDK-8.bat"
CALL "%SC_PYJA_HM%\Config\SSet-Anaconda3-5.1.0.bat"
CALL "%SC_PYJA_HM%\Config\SSet-Ruby-2.5.1.bat"

SET JAVA_HOME=%SC_J8_HM%

SET PYTHONHOME=%SC_PYTHON_HM%

SET SC_PATH=%PATH%

ECHO PATH =^> %SC_PATH%

ECHO MILO path =^> %SC_MILO_PN%
ECHO PYJA name =^> %SC_PYJA_NM%
ECHO PYJA version =^> %SC_PYJA_VR%
ECHO PYJA root =^> %SC_PYJA_RT%
ECHO PYJA home =^> %SC_PYJA_HM%

ECHO KAPA home =^> %SC_KAPA_HM%

ECHO Java home =^> %JAVA_HOME%

ECHO Python home =^> %PYTHONHOME%
ECHO Jep jar file =^> %SC_JEP_JAR_FN%

ECHO Ruby home =^> %SC_RUBY_HM%

"%SC_RUBY_EXE_FN%" "%SC_MILO_PN%\%SC_THIS_JN%.rb" %*

ENDLOCAL
