@ECHO OFF
SETLOCAL

SET PATH=%SystemRoot%\system32

SET SC_THIS_BN=%~NX0
SET SC_THIS_JN=%~N0

PUSHD "%~DP0"
CD "%~DP0"
SET SC_MILO_PN=%CD%
CD "%SC_MILO_PN%\..\..\.."
SET SC_PYJA_HM=%CD%
FOR %%F IN (%SC_PYJA_HM%) DO SET SC_PYJA_VR=%%~NXF
CD "%SC_PYJA_HM%\.."
SET SC_PYJA_RT=%CD%
FOR %%F IN (%SC_PYJA_RT%) DO SET SC_PYJA_NM=%%~NXF
POPD

CALL "%SC_PYJA_HM%\Config\SSet-KAPA.bat"
CALL "%SC_PYJA_HM%\Config\JDK\x64\SSet-JDK-8.bat"
CALL "%SC_PYJA_HM%\Config\JRuby\SSet-JRuby-9.2.5.0.bat"
CALL "%SC_PYJA_HM%\Config\Anaconda\x64\SSet-Anaconda-5.1.0.bat"

SET JAVA_HOME=%SC_J8_HM%

SET JRUBY_HOME=%SC_JRUBY_HM%
SET RUBYLIB=%SC_MILO_PN%

SET SC_PATH=%PATH%

ECHO PATH =^> %SC_PATH%

ECHO MILO path =^> %SC_MILO_PN%
ECHO KAPA home =^> %SC_KAPA_HM%
ECHO PYJA name =^> %SC_PYJA_NM%
ECHO PYJA version =^> %SC_PYJA_VR%
ECHO PYJA root =^> %SC_PYJA_RT%
ECHO PYJA home =^> %SC_PYJA_HM%

ECHO Java home =^> %JAVA_HOME%

ECHO JRuby home =^> %JRUBY_HOME%

SET SC_ALL_JARS="%SC_JRUBY_JAR_FN%"

"%SC_J8_X_FN%" -Dfile.encoding=UTF-8 -cp %SC_ALL_JARS% org.jruby.Main "%SC_MILO_PN%\%SC_THIS_JN%.rb" %*

ENDLOCAL
