SET SC_QTJ_HM=%SC_KAPA_HM%\19.01.22\Vindue\x32\QtJambi\4.5.2
SET SC_QTJ_LIB_PN=%SC_QTJ_HM%\bin
SET SC_QTJ_PLUGIN_PN=%SC_QTJ_HM%\plugins
SET SC_QTJ_JAR_FN=%SC_QTJ_HM%\qtjambi-4.5.2_01.jar
SET SC_QTJ_ALL_JARS="%SC_QTJ_HM%\qtjambi-examples-4.5.2_01.jar"
SET SC_QTJ_ALL_JARS=%SC_QTJ_ALL_JARS%;"%SC_QTJ_HM%\qtjambi-designer-4.5.2_01.jar"
SET SC_QTJ_ALL_JARS=%SC_QTJ_ALL_JARS%;"%SC_QTJ_JAR_FN%"
